[project]
name = "discord-bot"
version = "0.1.0"
description = "A simple Discord bot"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "discord.py",
    "python-dotenv",
    "requests",
] 
